version: '3'

services:
  # PostgreSQL
  db:
    image: postgres

  # Redis
  redis:
    image: redis

  # Memcache
  cache:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64

  # RabbitMQ
  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  # Django web server
  web:
    build: .
    # command: python3 manage.py createsuperuser 
    entrypoint: /app/docker-entrypoint.sh
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
      - redis
      - rabbitmq

  # Celery worker
  worker:
    build: .
    command: ./run_celery.sh
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
      - redis
      - cache