version: '3'

services:
  # PostgreSQL
  db:
    image: postgres

  # Redis
  redis:
    image: redis

  # Memcache
  cache:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64

  # RabbitMQ
  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  # Django web server
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    entrypoint: /app/web-entrypoint.sh
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media:/mnt/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
      - redis
      - rabbitmq

  media:
    build:
      context: .
      dockerfile: media.Dockerfile
    volumes:
      - media:/mnt/media
    ports:
      - "80:80"
    links:
      - web

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: web.Dockerfile
    command: ./run_celery.sh
    volumes:
      - .:/app
      - media:/mnt/media
    depends_on:
      - db
      - rabbitmq
      - redis
      - cache

  conversion_worker:
    build:
      context: .
      dockerfile: web.Dockerfile
    command: ./run_conversion_worker.sh
    volumes:
      - .:/app
      - media:/mnt/media
    depends_on:
      - db
      - rabbitmq
      - redis
      - cache

  # Celery beat scheduler
  beat:
    build:
      context: .
      dockerfile: web.Dockerfile
    command: ./run_beat.sh
    volumes:
      - .:/app
      - media:/mnt/media
    depends_on:
      - db
      - rabbitmq
      - redis
      - cache

volumes:
  media: