version: '3'

services:
  # PostgreSQL
  db:
    image: postgres

  # Memcache
  cache:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64

  # RabbitMQ
  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  # Django web server
  django:
    build:
      context: ./app
    command: bash -c "python3 manage.py migrate ; python3 manage.py collectstatic --noinput ; /usr/local/bin/gunicorn live2vod.wsgi:application -t 60 -w 2 --reload -b :8000"
    volumes:
      - ./app:/app
      - media:/srv/media
      - static:/srv/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
      - rabbitmq

  kaltura:
    build:
      context: ./kaltura
    volumes:
      - media:/srv/media
      - static:/srv/static
    ports:
      - "4010:4010"
    links:
      - django

  # Celery worker
  worker:
    build:
      context: ./app
    command: ./run_celery.sh
    volumes:
      - ./app:/app
      - media:/srv/media
    depends_on:
      - db
      - rabbitmq
      - cache

  # conversion_worker:
  #   build:
  #     context: ./app
  #   command: ./run_conversion_worker.sh
  #   volumes:
  #     - ./app:/app
  #     - media:/srv/media
  #   depends_on:
  #     - db
  #     - rabbitmq
  #     - cache

  # Celery beat scheduler
  beat:
    build:
      context: ./app
    command: ./run_beat.sh
    volumes:
      - ./app:/app
      - media:/srv/media
    depends_on:
      - db
      - rabbitmq
      - cache

volumes:
  media:
  static:
