# Generated by Django 2.0rc1 on 2017-12-04 05:15

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dvr', '0003_auto_20171203_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Waiting'), (1, 'Queued'), (2, 'Running'), (3, 'Success'), (4, 'Failure')], db_index=True, default=0, verbose_name='status')),
                ('progress', models.FloatField(blank=True, null=True, verbose_name='progress')),
                ('result', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='result')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('metadata', django.contrib.postgres.fields.hstore.HStoreField(null=True, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'distribution attempt',
                'verbose_name_plural': 'distribution attempts',
            },
        ),
        migrations.CreateModel(
            name='DistributionChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('metadata', django.contrib.postgres.fields.hstore.HStoreField(null=True, verbose_name='metadata')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('type', models.CharField(choices=[('multimedia', 'multimedia'), ('ftp', 'FTP'), ('youtube', 'YouTube')], max_length=128, verbose_name='type')),
            ],
            options={
                'verbose_name': 'distribution channel',
                'verbose_name_plural': 'distribution channels',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Waiting'), (1, 'Queued'), (2, 'Running'), (3, 'Success'), (4, 'Failure')], db_index=True, default=0, verbose_name='status')),
                ('progress', models.FloatField(blank=True, null=True, verbose_name='progress')),
                ('result', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='result')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('metadata', django.contrib.postgres.fields.hstore.HStoreField(null=True, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='conversion',
        ),
        migrations.AlterModelOptions(
            name='conversion',
            options={'ordering': ('-start',), 'verbose_name': 'conversion', 'verbose_name_plural': 'conversions'},
        ),
        migrations.RemoveField(
            model_name='conversion',
            name='priority',
        ),
        migrations.AddField(
            model_name='conversion',
            name='progress',
            field=models.FloatField(blank=True, null=True, verbose_name='progress'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='source URL'),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='result',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='result'),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='dvr.Stream', verbose_name='stream'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.DeleteModel(
            name='Distribution',
        ),
        migrations.AddField(
            model_name='video',
            name='conversions',
            field=models.ManyToManyField(blank=True, to='dvr.Conversion', verbose_name='conversions'),
        ),
        migrations.AddField(
            model_name='distributionattempt',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvr.DistributionChannel', verbose_name='channel'),
        ),
        migrations.AddField(
            model_name='distributionattempt',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_attempts', to='dvr.Video', verbose_name='video'),
        ),
    ]
