# Generated by Django 2.0 on 2017-12-14 04:53

from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dvr', '0012_auto_20171214_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('metadata', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name='metadata')),
                ('configuration', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name='configuration')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(blank=True, default='', max_length=255, unique=True, verbose_name='slug')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='dvr.DistributionChannel', verbose_name='channel')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributionprofile_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributionprofile_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name': 'distribution profile',
                'verbose_name_plural': 'distribution profiles',
            },
        ),
    ]
