# Generated by Django 2.0 on 2017-12-30 09:27

from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dvr', '0015_auto_20171219_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], db_index=True, default='PENDING', max_length=32, verbose_name='status')),
                ('progress', models.FloatField(blank=True, null=True, verbose_name='progress')),
                ('result', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name='result')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('end', models.DateTimeField(verbose_name='end')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sceneanalysis_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sceneanalysis_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_analysis', to='dvr.Stream', verbose_name='stream')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SceneChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('time', models.DateTimeField(verbose_name='time')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='value')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenechange_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenechange_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('scene_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_changes', to='dvr.SceneAnalysis', verbose_name='scene analysis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='video',
            name='configuration',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name='configuration'),
        ),
    ]
