# Generated by Django 2.0.1 on 2018-01-26 06:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvr', '0017_auto_20180102_0440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributionattempt',
            options={'ordering': ['-created_at'], 'verbose_name': 'distribution attempt', 'verbose_name_plural': 'distribution attempts'},
        ),
        migrations.AlterModelOptions(
            name='distributionprofile',
            options={'ordering': ['channel', '-created_at'], 'verbose_name': 'distribution profile', 'verbose_name_plural': 'distribution profiles'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at'], 'verbose_name': 'video', 'verbose_name_plural': 'videos'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='conversions',
        ),
        migrations.AddField(
            model_name='video',
            name='sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=[], size=None, verbose_name='sources'),
            preserve_default=False,
        ),
    ]
