# Generated by Django 2.0 on 2017-12-14 04:27

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvr', '0011_auto_20171214_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='result',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name='result'),
        ),
        migrations.AlterField(
            model_name='distributionattempt',
            name='result',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name='result'),
        ),
        migrations.AlterField(
            model_name='video',
            name='result',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name='result'),
        ),
    ]
