# Generated by Django 2.0.1 on 2018-01-26 07:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvr', '0019_auto_20180126_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='stream',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='dvr.Stream', verbose_name='stream'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='images'), blank=True, default=[], size=None, verbose_name='thumbnails'),
        ),
    ]
