# Generated by Django 2.0.1 on 2018-01-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvr', '0020_auto_20180126_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='timestamp_end',
        ),
        migrations.RemoveField(
            model_name='video',
            name='timestamp_start',
        ),
        migrations.AddField(
            model_name='video',
            name='end',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='end'),
        ),
        migrations.AddField(
            model_name='video',
            name='start',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='start'),
        ),
    ]
