# Generated by Django 2.0.2 on 2018-02-12 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dvr', '0027_auto_20180211_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('type', models.CharField(choices=[('opening_sequence', 'Opening sequence'), ('closing_sequence', 'Closing sequence'), ('pause_sequence', 'Pause sequence'), ('cameback_sequence', 'Cameback sequence')], db_index=True, max_length=32, verbose_name='type')),
                ('time', models.DateTimeField(db_index=True, verbose_name='time')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foundsequence_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foundsequence_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'ordering': ['-time', 'created_at'],
                'verbose_name': 'found sequence',
                'verbose_name_plural': 'found sequences',
            },
        ),
        migrations.RemoveField(
            model_name='sceneseries',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sceneseries',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='sceneseries',
            name='scene_analysis',
        ),
        migrations.RemoveField(
            model_name='sceneseries',
            name='series',
        ),
        migrations.AddField(
            model_name='series',
            name='cameback_sequence_offset',
            field=models.DurationField(default=timedelta, verbose_name='cameback sequence offset'),
        ),
        migrations.AddField(
            model_name='series',
            name='closing_sequence_offset',
            field=models.DurationField(default=timedelta, verbose_name='closing sequence offset'),
        ),
        migrations.AddField(
            model_name='series',
            name='opening_sequence_offset',
            field=models.DurationField(default=timedelta, verbose_name='opening sequence offset'),
        ),
        migrations.AddField(
            model_name='series',
            name='pause_sequence_offset',
            field=models.DurationField(default=timedelta, verbose_name='pause sequence offset'),
        ),
        migrations.AlterField(
            model_name='series',
            name='closing_sequence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closing_sequence_series', to='dvr.Video', verbose_name='closing sequence'),
        ),
        migrations.AlterField(
            model_name='series',
            name='comeback_sequence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameback_sequence_series', to='dvr.Video', verbose_name='comeback sequence'),
        ),
        migrations.AlterField(
            model_name='series',
            name='opening_sequence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_sequence_series', to='dvr.Video', verbose_name='opening sequence'),
        ),
        migrations.AlterField(
            model_name='series',
            name='pause_sequence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pause_sequence_series', to='dvr.Video', verbose_name='pause sequence'),
        ),
        migrations.DeleteModel(
            name='SceneSeries',
        ),
        migrations.AddField(
            model_name='foundsequence',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_sequences', to='dvr.Series', verbose_name='series'),
        ),
    ]
