# Generated by Django 2.0 on 2017-12-19 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvr', '0014_auto_20171214_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionattempt',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='dvr.DistributionProfile', verbose_name='profile'),
        ),
    ]
