# Generated by Django 2.0.2 on 2018-02-11 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dvr', '0025_auto_20180208_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='modified at')),
                ('type', models.CharField(choices=[('OPENING', 'Opening'), ('ENDING', 'Ending'), ('PAUSE', 'Pause'), ('CAMEBACK', 'Came back')], db_index=True, max_length=16, verbose_name='type')),
                ('time', models.DateTimeField(db_index=True, verbose_name='time')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sceneseries_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sceneseries_modified', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'scene series',
                'ordering': ['-time', 'created_at'],
                'verbose_name': 'scene series',
            },
        ),
        migrations.AlterField(
            model_name='conversion',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='start',
            field=models.DateTimeField(db_index=True, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='distributionattempt',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='distributionattempt',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_attempts', to='dvr.DistributionProfile', verbose_name='profile'),
        ),
        migrations.AlterField(
            model_name='distributionchannel',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='distributionchannel',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='distributionchannel',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='distributionchannel',
            name='type',
            field=models.CharField(choices=[('MULTIMEDIA', 'Captura-Multimedia'), ('FTP', 'FTP'), ('YOUTUBE', 'YouTube')], db_index=True, max_length=16, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='distributionprofile',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='distributionprofile',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='distributionprofile',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sceneanalysis',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='scenechange',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='scenechange',
            name='time',
            field=models.DateTimeField(db_index=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='series',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='seriesrecurrence',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='sceneseries',
            name='scene_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_series', to='dvr.SceneAnalysis', verbose_name='scene analysis'),
        ),
        migrations.AddField(
            model_name='sceneseries',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_series', to='dvr.Series', verbose_name='series'),
        ),
    ]
