# Generated by Django 2.0.2 on 2018-02-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvr', '0026_auto_20180211_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'permissions': (('view_stream', 'View stream'),), 'verbose_name': 'stream', 'verbose_name_plural': 'streams'},
        ),
    ]
